# Generated by Django 5.1 on 2025-02-17 06:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_ai_total_marks_question_answers_question_marks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=50)),
                ('topic_code', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('question_image', models.TextField(blank=True, null=True)),
                ('typed', models.TextField(blank=True, null=True)),
                ('sub_topic_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='class_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question_answers',
            name='answer_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_answers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 6, 18, 51, 747735, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question_answers',
            name='topic',
            field=models.ManyToManyField(blank=True, to='myapp.topics'),
        ),
        migrations.CreateModel(
            name='StudentSubmits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('question', models.TextField()),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('correction_text', models.TextField(blank=True, null=True)),
                ('mistakes', models.TextField(blank=True, null=True)),
                ('question_marks', models.IntegerField(blank=True, null=True)),
                ('student_marks', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('concepts_used', models.JSONField(blank=True, null=True)),
                ('student_answer_replication', models.TextField(blank=True, null=True)),
                ('correct_answer_breakdown', models.JSONField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
