# Generated by Django 5.1 on 2025-04-25 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_questionwithimage_classes_class_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('chapter_number', models.TextField(blank=True, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_image_base64', models.TextField(blank=True, null=True)),
                ('student_answer_base64', models.TextField(blank=True, null=True)),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('student_score', models.IntegerField(blank=True, null=True)),
                ('answering_type', models.TextField(blank=True, max_length=50, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
