# Generated by Django 5.1 on 2025-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_gapanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysis',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
