# Generated by Django 5.1 on 2025-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_gapanalysis_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysis',
            name='ai_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='concept_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
