# Generated by Django 5.1 on 2025-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gapanalysis_ai_answer_gapanalysis_concept_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysis',
            name='student_answering_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
