# Generated by Django 5.1 on 2024-08-28 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.CreateModel(
            name='Question_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('exercise', models.BooleanField(default=False)),
                ('externel', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_answer', models.TextField()),
                ('ai_correction', models.TextField(blank=True, max_length=100, null=True)),
                ('ai_given_marks', models.IntegerField()),
                ('ai_total_marks', models.IntegerField()),
                ('ai_concepts', models.TextField()),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopics')),
                ('topic', models.ManyToManyField(blank=True, null=True, to='myapp.topics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
