# Generated by Django 5.1 on 2024-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answers',
            name='ai_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_answers',
            name='ai_concepts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_answers',
            name='ai_given_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_answers',
            name='ai_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_answers',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_answers',
            name='topic',
            field=models.ManyToManyField(to='myapp.topics'),
        ),
    ]
