# Generated by Django 5.1 on 2024-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_question_answers_ai_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_answers',
            old_name='ai_total_marks',
            new_name='question_marks',
        ),
        migrations.RemoveField(
            model_name='question_answers',
            name='ai_correction',
        ),
        migrations.AddField(
            model_name='question_answers',
            name='ai_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_answers',
            name='ai_explain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_answers',
            name='ai_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_answers',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_answers',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
